export const company = {
 name: 'Aarvan Labs', founder: 'Arivumathi S', description: 'Aarvan Labs is a Chennai-based AI and automation studio founded by Arivumathi S, operating under Aarvan Technology.',
 socials: ['https://arivumathi.in','https://github.com/Arivumathi323','https://www.linkedin.com/in/arivumathi-s-aarvan-labs/','https://youtube.com/@aarvan_labs','https://www.instagram.com/learn_with_aarvan'],
 timeline: [{year:'TODO: Year',milestone:'Started coding on a mobile phone'},{year:'TODO: Year',milestone:'Began B.E. Computer Science studies in Chennai'},{year:'TODO: Year',milestone:'Founded Aarvan Labs'}],
 photo: '/images/arivu.jpg', // TODO: Add founder photo at this path.
 testimonials: [], // Only add testimonials supplied by real customers with permission.
};
const service = (slug,name,h1,intro,audience,deliverables,cases,tools,project,learn,faqs) => ({slug,name,h1,intro,audience,deliverables,cases,tools,project,learn,faqs,prices:[{name:'Focused build',price:null},{name:'Connected system',price:null}],timeline:['Discover: 1–3 working days to map the workflow','Design: 2–5 working days to agree the scope','Build: typically 1–4 weeks, depending on integrations','Support: handover and support period agreed in your proposal']}); // TODO: Set service prices and confirm indicative timelines.
export const services = [
 service('website-development','Website Development','Website Development Company in Chennai','Website development is the design and engineering of a fast, accessible home for your business online. Aarvan Labs, based in Chennai, builds business websites and landing pages that turn clear information into useful enquiries.', ['Local businesses','EV and engineering firms','Colleges','Independent professionals'],['Responsive page layouts','Accessible navigation and forms','Search metadata and structured data','Working enquiry flow','Performance checks','Deployment and editing handover'],['A clinic presenting treatments and appointment enquiries','An engineering firm explaining its capabilities','A coaching centre collecting course enquiries'],['HTML / CSS','Next.js','Vercel','Supabase'],'KONSOLV','seo-aeo-for-business',[
 ['Can you update an existing website?','Yes. We first review its structure and preserve useful content, URLs and brand styling.'],['Will the website work on phones?','Layouts, navigation and forms are checked at mobile and desktop sizes.'],['Can you build with Next.js?','Yes. We choose Next.js or a simpler static approach based on the required features.'],['Does a new website guarantee rankings?','No. Technical SEO makes content accessible, while rankings also depend on competition, relevance and ongoing work.'],['Who owns the finished site?','Ownership, hosting access and source handover are documented in the proposal.']]),
 service('n8n-automation','n8n Automation','n8n Automation Expert in Chennai','n8n automation connects business tools into workflows that run on a trigger or schedule. Aarvan Labs, based in Chennai, builds n8n workflows that move information reliably and give your team visibility when a step fails.', ['Sales teams','Coaching centres','Retail operations','Small agencies'],['Workflow discovery map','Configured triggers and integrations','Validation and duplicate handling','Error alerts and retry paths','Credential setup guidance','Workflow documentation and training'],['Send website leads to a CRM and alert a sales owner','Prepare daily sales summaries for a retailer','Route college admissions enquiries to the right team'],['n8n','Webhooks','Google Sheets','OpenAI / Claude'],'GEO Audit Engine','ai-automation-course',[
 ['Can n8n replace Zapier?','Often, but we check your integrations and maintenance needs before recommending a migration.'],['Can n8n be self-hosted?','Yes. Hosting, backups and updates need an owner; we discuss those responsibilities before launch.'],['What happens when a workflow fails?','We design alerts and recovery paths for the agreed failure cases.'],['Do all workflows need AI?','No. Rules and ordinary integrations are usually better for predictable tasks.'],['Are tool subscriptions included?','Hosting, model usage and third-party subscriptions are scoped separately in the quote.']]),
 service('ai-agent-development','AI Agent Development','AI Agent Development Services','AI agent development creates software that uses a language model, business knowledge and approved tools to complete a defined task. Aarvan Labs, based in Chennai, builds custom AI agents with clear boundaries and human handover.', ['Customer support teams','Professional services','Education teams','Internal operations'],['Task and permission specification','Knowledge retrieval setup','Approved tool integrations','Human handover flow','Evaluation examples','Monitoring and handover notes'],['Answer admissions questions from approved college documents','Help a support team draft answers with source references','Assist sales staff with a structured lead summary'],['OpenAI / Claude','Supabase','n8n','APIs'],'NOVA','ai-automation-course',[
 ['How is an agent different from a chatbot?','A chatbot primarily replies; an agent can use approved tools to carry out a defined workflow.'],['Can it use our documents?','Yes, subject to access permissions and a review of document quality and freshness.'],['Can an AI agent make mistakes?','Yes. We use evaluations, source grounding and human review for consequential actions.'],['Can it connect to our CRM?','Usually, when the CRM provides a suitable API and account permissions.'],['How are running costs estimated?','We estimate model usage, storage and integration costs from the expected workload.']]),
 service('agentic-ai-system-design','Agentic AI System Design','Agentic AI System Design & Consulting','Agentic AI system design defines how models, tools, memory and human decisions work together. Aarvan Labs, based in Chennai, helps teams design AI architectures with explicit permissions, testable behavior and manageable operating costs.', ['Product founders','Engineering teams','Automation agencies','Growing SMBs'],['Architecture and data-flow map','Agent responsibility definitions','Tool and MCP integration plan','Permission and approval boundaries','Evaluation and observability plan','Implementation roadmap'],['Plan a multi-step customer support workflow','Design an internal research assistant with source checks','Separate lead research from human-approved outreach'],['MCP','OpenAI / Claude','n8n','Supabase'],'AARVAN VISION OS','one-on-one-mentorship',[
 ['Do we need multiple agents?','Only if distinct responsibilities justify the complexity. A single workflow is often enough.'],['What is MCP used for?','MCP gives compatible AI systems a standard way to access tools and context.'],['Can you review an existing architecture?','Yes. We can assess data flow, reliability, permissions and evaluation coverage.'],['Is implementation included?','Consulting and implementation are separate scopes, agreed before work begins.'],['How do you control autonomous actions?','We define allowed tools and require human approval for consequential operations.']]),
 service('business-automation','Business Automation','Business Process Automation for SMBs','Business process automation uses software to handle repetitive operational steps with consistent rules. Aarvan Labs, based in Chennai, connects lead capture, CRM updates and team notifications so small businesses spend less time copying data.', ['Retailers','Real estate teams','Restaurants','Service businesses'],['Current-process audit','Prioritized automation plan','Connected lead capture','CRM and spreadsheet updates','Approval and exception handling','Staff training'],['Assign real estate enquiries to available agents','Consolidate restaurant catering requests','Remind a service team about pending follow-ups'],['n8n','CRM APIs','Google Sheets','Webhooks'],'KONSOLV','ai-automation-course',[
 ['Where should a small business start?','Start with one repetitive process that has a clear owner, inputs and measurable outcome.'],['Can we keep our existing tools?','Usually. We check their APIs and export options during discovery.'],['Will this replace our team?','The aim is to reduce repetitive work and give people clearer exceptions to resolve.'],['Can you automate approvals?','We can route and record approvals while keeping the actual decision with the right person.'],['How is success measured?','We agree practical measures such as time per enquiry, missed handoffs and error rates.']]),
 service('whatsapp-automation','WhatsApp Automation','WhatsApp Automation for Business in Chennai','WhatsApp automation connects a business messaging account to structured replies and workflows. Aarvan Labs, based in Chennai, builds WhatsApp chatbot flows for enquiries, bookings and customer handover using approved business integrations.', ['Clinics','Coaching centres','Retail shops','Real estate teams'],['Account and API setup guidance','Enquiry and reply flow design','Approved template setup support','CRM or booking integration','Human handover','Consent and opt-out flow','Testing and handover'],['Route clinic appointment requests','Answer course questions at a coaching centre','Send opted-in order updates for a retailer'],['WhatsApp Cloud API','n8n','Webhooks','Supabase'],'NOVA','whatsapp-automation-course',[
 ['Do I need a WhatsApp Business API account?','API-based workflows require an eligible business setup. We review your account before proposing the integration.'],['Can customers reach a person?','Yes. Handover rules are part of the flow design.'],['Can the bot answer in Tamil?','We can design Tamil and English content and test it with your team.'],['How much does WhatsApp automation cost in India?','Setup depends on the flow and integrations. Platform and message charges are separate and confirmed during scoping.'],['Can I message purchased contact lists?','We design flows for customers who have opted in, with clear opt-out handling.']]),
 service('ai-receptionist','AI Receptionist','AI Receptionist for Business (Voice AI)','An AI receptionist is a voice assistant that answers calls and handles defined front-desk tasks. Aarvan Labs, based in Chennai, builds voice AI for enquiries, appointment requests and call summaries, with escalation to your team.', ['Clinics','Salons','Property businesses','Professional offices'],['Call-flow and escalation design','Voice and language configuration','Business knowledge setup','Appointment integration','Call summaries','Scenario testing','Team handover'],['Handle after-hours appointment requests at a clinic','Collect property enquiry details','Answer office opening-hour questions'],['Twilio','OpenAI / Claude','n8n','Calendar APIs'],'NOVA','one-on-one-mentorship',[
 ['What is an AI receptionist?','It is a voice assistant configured to answer business calls and complete an agreed set of tasks.'],['Can it speak Tamil?','Tamil and English support can be scoped and tested for your callers and selected voice provider.'],['Can it book appointments?','Yes, when a suitable calendar or booking API is available and the availability rules are clear.'],['What if it cannot answer a question?','It should take a message or transfer to a person according to the agreed escalation rules.'],['Are recordings always enabled?','No. Recording, disclosure and retention settings are agreed for the business before launch.']]),
];
const course = (slug,name,h1,intro,audience,modules,outcomes) => ({slug,name,h1,intro,audience,modules,outcomes,price:null,format:'Online; Chennai in-person availability by arrangement.',schedule:'TODO: Confirm session length, total duration, batch or 1:1 availability, and upcoming dates.',certificate:'TODO: Confirm whether a certificate is offered.',faqs:[['Do I need prior experience?','We review your starting point before booking and recommend prerequisites for the selected syllabus.'],['Will I build a project?','Yes. Sessions connect the concepts to a practical workflow or business project.'],['Can I learn in Tamil?','Tamil and English support is available; discuss your preferred language when enquiring.'],['What does the fee include?','Session scope, support and any separate tool costs are confirmed before payment.']]});
export const learn = [
 course('one-on-one-mentorship','1:1 Mentorship','1:1 AI & Automation Mentorship','AI and automation mentorship is personal guidance for learning to build useful software and workflows. Arivu at Aarvan Labs in Chennai helps you work through a project, understand your choices and develop your own problem-solving process.',['Students','Founders','Freelancers'],['Define your goal and review your starting point','Map a small, achievable project','Build workflows, APIs or an AI agent together','Debug, test and plan your next steps'],['A focused learning plan','A reviewed project','A clear next-step roadmap']),
 course('ai-automation-course','AI Automation Course','AI Automation Course (n8n + AI Agents)','An AI automation course teaches you to combine workflow tools, APIs and language models into useful systems. Aarvan Labs in Chennai teaches n8n and AI agents through practical builds and testing.',['Students','Freelancers','Operations teams'],['Workflow basics: triggers, data and expressions','APIs, webhooks and credentials','Build a lead capture workflow in n8n','Connect an AI model and business knowledge','Add tool boundaries, retries and human review','Build and present a working automation project'],['A lead routing workflow','A grounded AI assistant prototype','Experience testing and debugging workflows']),
 course('whatsapp-automation-course','WhatsApp Automation Training','WhatsApp Automation Training','WhatsApp automation training teaches you to design and connect business messaging workflows. Aarvan Labs in Chennai guides you from WhatsApp Cloud API concepts to a practical enquiry flow with human handover.',['Business owners','Freelancers','Support teams'],['Business account and WhatsApp Cloud API fundamentals','Webhooks and incoming message handling','Conversation design and approved templates','Connect a CRM or booking workflow','Add consent, opt-out and human handover','Test a real business enquiry project'],['A documented messaging flow','A tested integration prototype','A handover and maintenance checklist']),
 course('seo-aeo-for-business','SEO, AEO & GEO Training','SEO, AEO & GEO Training for Businesses','SEO, AEO and GEO training explains how websites can be discovered, understood and referenced by search and AI answer engines. Aarvan Labs in Chennai teaches businesses to improve accessible content and run a hands-on audit with the GEO Audit Engine.',['Business owners','Marketing teams','Website builders'],['SEO fundamentals: crawling, indexing and intent','AEO: answering a clear question directly','GEO: consistent entities, evidence and useful sources','Review metadata, structure and internal links','Run a hands-on GEO Audit Engine review','Prioritize improvements and track visibility'],['A website audit','A prioritized content plan','An understanding of citation limits'])
];
learn[3].faqs.push(['Can you guarantee citations in ChatGPT, Gemini or Perplexity?','No. Clear, accurate, accessible content can help discovery, but each platform controls its own answers and citations.']);
export const homeFaq = [ ['What is Aarvan Labs?',company.description], ['What can you build for my business?','Websites, n8n workflows, custom AI agents, business automations, WhatsApp flows and voice AI receptionists.'], ['Do you teach as well as build?','Yes. Learn with Aarvan includes 1:1 mentorship and practical AI, WhatsApp and search visibility training.'], ['Can we work together outside Chennai?','Yes. Remote discovery, delivery and online learning can be arranged across India.'], ['Is Tamil support available?','Yes. We support conversations and learning in Tamil and English.'], ['How much does a project cost?','We quote after understanding the scope, integrations and ongoing support. Published prices are awaiting confirmation.'], ['How do I get started?','Book a free call or send the contact form with your goal and current setup.'] ];
export const processSteps = ['Discover — understand your goal and current workflow','Design — agree the scope, tools and success criteria','Build — implement, test and review together','Support — hand over the system and plan ongoing care'];
export const why = ['Real product experience with THOZHAN, NOVA and VISION OS','Tamil and English support','Focused scope and short delivery cycles','We teach you how the system works'];

const outcomes = ['Turn website visits into useful business enquiries','Move data between your tools without repetitive copying','Give your team an assistant grounded in business knowledge','Plan reliable AI systems with clear responsibilities','Keep leads and operational handoffs moving','Handle customer enquiries and hand over to your team','Answer calls and capture appointment requests'];
services.forEach((s,i)=>s.summary=outcomes[i]);
