export const company = {
 name: 'Aarvan Labs', phone: '+918122167396', phoneDisplay: '+91 8122167396', founder: 'Arivumathi S', description: 'Aarvan Labs is a Chennai-based AI and automation studio founded by Arivumathi S, operating under Aarvan Technology.',
 socials: ['https://www.arivumathi.in/','https://github.com/Arivumathi323','https://www.linkedin.com/in/arivumathi-s-aarvan-labs/','https://youtube.com/@aarvan_labs','https://www.instagram.com/learn_with_aarvan'],
 timeline: [{year:'TODO: Year',milestone:'Started coding on a mobile phone'},{year:'TODO: Year',milestone:'Began B.E. Computer Science studies in Chennai'},{year:'TODO: Year',milestone:'Founded Aarvan Labs'}],
 photo: '/images/arivu.webp',
 testimonials: [], // Only add testimonials supplied by real customers with permission.
};
const service = (slug,name,h1,intro,audience,deliverables,cases,tools,project,learn,faqs) => ({slug,name,h1,intro,audience,deliverables,cases,tools,project,learn,faqs,prices:[{name:'Focused build',price:null},{name:'Connected system',price:null}],timeline:['Discover: 1–3 working days to map the workflow','Design: 2–5 working days to agree the scope','Build: typically 1–4 weeks, depending on integrations','Support: handover and support period agreed in your proposal']}); // TODO: Set service prices and confirm indicative timelines.
export const services = [
 service('website-development','Website Development','Website Development Company in Chennai','Website development is the design and engineering of a fast, accessible home for your business online. Aarvan Labs, based in Chennai, builds business websites and landing pages that turn clear information into useful enquiries.', ['Local businesses','EV and engineering firms','Colleges','Independent professionals'],['Responsive page layouts','Accessible navigation and forms','Search metadata and structured data','Working enquiry flow','Performance checks','Deployment and editing handover'],['A clinic presenting treatments and appointment enquiries','An engineering firm explaining its capabilities','A coaching centre collecting course enquiries'],['HTML / CSS','Next.js','Vercel','Supabase'],'KONSOLV','seo-aeo-for-business',[
 ['Can you update an existing website?','Yes. We first review its structure and preserve useful content, URLs and brand styling.'],['Will the website work on phones?','Layouts, navigation and forms are checked at mobile and desktop sizes.'],['Can you build with Next.js?','Yes. We choose Next.js or a simpler static approach based on the required features.'],['Does a new website guarantee rankings?','No. Technical SEO makes content accessible, while rankings also depend on competition, relevance and ongoing work.'],['Who owns the finished site?','Ownership, hosting access and source handover are documented in the proposal.']]),
 service('n8n-automation','n8n Automation','n8n Automation Expert in Chennai','n8n automation connects business tools into workflows that run on a trigger or schedule. Aarvan Labs, based in Chennai, builds n8n workflows that move information reliably and give your team visibility when a step fails.', ['Sales teams','Coaching centres','Retail operations','Small agencies'],['Workflow discovery map','Configured triggers and integrations','Validation and duplicate handling','Error alerts and retry paths','Credential setup guidance','Workflow documentation and training'],['Send website leads to a CRM and alert a sales owner','Prepare daily sales summaries for a retailer','Route college admissions enquiries to the right team'],['n8n','Webhooks','Google Sheets','OpenAI / Claude'],'GEO Audit Engine','ai-automation-course',[
 ['Can n8n replace Zapier?','Often, but we check your integrations and maintenance needs before recommending a migration.'],['Can n8n be self-hosted?','Yes. Hosting, backups and updates need an owner; we discuss those responsibilities before launch.'],['What happens when a workflow fails?','We design alerts and recovery paths for the agreed failure cases.'],['Do all workflows need AI?','No. Rules and ordinary integrations are usually better for predictable tasks.'],['Are tool subscriptions included?','Hosting, model usage and third-party subscriptions are scoped separately in the quote.']]),
 service('ai-agent-development','AI Agent Development','AI Agent Development Services','AI agent development creates software that uses a language model, business knowledge and approved tools to complete a defined task. Aarvan Labs, based in Chennai, builds custom AI agents with clear boundaries and human handover.', ['Customer support teams','Professional services','Education teams','Internal operations'],['Task and permission specification','Knowledge retrieval setup','Approved tool integrations','Human handover flow','Evaluation examples','Monitoring and handover notes'],['Answer admissions questions from approved college documents','Help a support team draft answers with source references','Assist sales staff with a structured lead summary'],['OpenAI / Claude','Supabase','n8n','APIs'],'NOVA','ai-automation-course',[
 ['How is an agent different from a chatbot?','A chatbot primarily replies; an agent can use approved tools to carry out a defined workflow.'],['Can it use our documents?','Yes, subject to access permissions and a review of document quality and freshness.'],['Can an AI agent make mistakes?','Yes. We use evaluations, source grounding and human review for consequential actions.'],['Can it connect to our CRM?','Usually, when the CRM provides a suitable API and account permissions.'],['How are running costs estimated?','We estimate model usage, storage and integration costs from the expected workload.']]),
 service('agentic-ai-system-design','Agentic AI System Design','Agentic AI System Design & Consulting','Agentic AI system design defines how models, tools, memory and human decisions work together. Aarvan Labs, based in Chennai, helps teams design AI architectures with explicit permissions, testable behavior and manageable operating costs.', ['Product founders','Engineering teams','Automation agencies','Growing SMBs'],['Architecture and data-flow map','Agent responsibility definitions','Tool and MCP integration plan','Permission and approval boundaries','Evaluation and observability plan','Implementation roadmap'],['Plan a multi-step customer support workflow','Design an internal research assistant with source checks','Separate lead research from human-approved outreach'],['MCP','OpenAI / Claude','n8n','Supabase'],'AARVAN VISION OS','one-on-one-mentorship',[
 ['Do we need multiple agents?','Only if distinct responsibilities justify the complexity. A single workflow is often enough.'],['What is MCP used for?','MCP gives compatible AI systems a standard way to access tools and context.'],['Can you review an existing architecture?','Yes. We can assess data flow, reliability, permissions and evaluation coverage.'],['Is implementation included?','Consulting and implementation are separate scopes, agreed before work begins.'],['How do you control autonomous actions?','We define allowed tools and require human approval for consequential operations.']]),
 service('business-automation','Business Automation','Business Process Automation for SMBs','Business process automation uses software to handle repetitive operational steps with consistent rules. Aarvan Labs, based in Chennai, connects lead capture, CRM updates and team notifications so small businesses spend less time copying data.', ['Retailers','Real estate teams','Restaurants','Service businesses'],['Current-process audit','Prioritized automation plan','Connected lead capture','CRM and spreadsheet updates','Approval and exception handling','Staff training'],['Assign real estate enquiries to available agents','Consolidate restaurant catering requests','Remind a service team about pending follow-ups'],['n8n','CRM APIs','Google Sheets','Webhooks'],'KONSOLV','ai-automation-course',[
 ['Where should a small business start?','Start with one repetitive process that has a clear owner, inputs and measurable outcome.'],['Can we keep our existing tools?','Usually. We check their APIs and export options during discovery.'],['Will this replace our team?','The aim is to reduce repetitive work and give people clearer exceptions to resolve.'],['Can you automate approvals?','We can route and record approvals while keeping the actual decision with the right person.'],['How is success measured?','We agree practical measures such as time per enquiry, missed handoffs and error rates.']]),
 service('whatsapp-automation','WhatsApp Automation','WhatsApp Automation for Business in Chennai','WhatsApp automation connects a business messaging account to structured replies and workflows. Aarvan Labs, based in Chennai, builds WhatsApp chatbot flows for enquiries, bookings and customer handover using approved business integrations.', ['Clinics','Coaching centres','Retail shops','Real estate teams'],['Account and API setup guidance','Enquiry and reply flow design','Approved template setup support','CRM or booking integration','Human handover','Consent and opt-out flow','Testing and handover'],['Route clinic appointment requests','Answer course questions at a coaching centre','Send opted-in order updates for a retailer'],['WhatsApp Cloud API','n8n','Webhooks','Supabase'],'NOVA','whatsapp-automation-course',[
 ['Do I need a WhatsApp Business API account?','API-based workflows require an eligible business setup. We review your account before proposing the integration.'],['Can customers reach a person?','Yes. Handover rules are part of the flow design.'],['Can the bot answer in Tamil?','We can design Tamil and English content and test it with your team.'],['How much does WhatsApp automation cost in India?','Setup depends on the flow and integrations. Platform and message charges are separate and confirmed during scoping.'],['Can I message purchased contact lists?','We design flows for customers who have opted in, with clear opt-out handling.']]),
 service('ai-receptionist','AI Receptionist','AI Receptionist for Business (Voice AI)','An AI receptionist is a voice assistant that answers calls and handles defined front-desk tasks. Aarvan Labs, based in Chennai, builds voice AI for enquiries, appointment requests and call summaries, with escalation to your team.', ['Clinics','Salons','Property businesses','Professional offices'],['Call-flow and escalation design','Voice and language configuration','Business knowledge setup','Appointment integration','Call summaries','Scenario testing','Team handover'],['Handle after-hours appointment requests at a clinic','Collect property enquiry details','Answer office opening-hour questions'],['Twilio','OpenAI / Claude','n8n','Calendar APIs'],'NOVA','one-on-one-mentorship',[
 ['What is an AI receptionist?','It is a voice assistant configured to answer business calls and complete an agreed set of tasks.'],['Can it speak Tamil?','Tamil and English support can be scoped and tested for your callers and selected voice provider.'],['Can it book appointments?','Yes, when a suitable calendar or booking API is available and the availability rules are clear.'],['What if it cannot answer a question?','It should take a message or transfer to a person according to the agreed escalation rules.'],['Are recordings always enabled?','No. Recording, disclosure and retention settings are agreed for the business before launch.']]),
];
const course = (slug,name,h1,intro,audience,modules,outcomes) => ({slug,name,h1,intro,audience,modules,outcomes,price:null,format:'Online; Chennai in-person availability by arrangement.',schedule:'TODO: Confirm session length, total duration, batch or 1:1 availability, and upcoming dates.',certificate:'TODO: Confirm whether a certificate is offered.',faqs:[['Do I need prior experience?','We review your starting point before booking and recommend prerequisites for the selected syllabus.'],['Will I build a project?','Yes. Sessions connect the concepts to a practical workflow or business project.'],['Can I learn in Tamil?','Tamil and English support is available; discuss your preferred language when enquiring.'],['What does the fee include?','Session scope, support and any separate tool costs are confirmed before payment.']]});
export const learn = [
 course('one-on-one-mentorship','1:1 Mentorship','1:1 AI & Automation Mentorship','AI and automation mentorship is personal guidance for learning to build useful software and workflows. Arivu at Aarvan Labs in Chennai helps you work through a project, understand your choices and develop your own problem-solving process.',['Students','Founders','Freelancers'],['Define your goal and review your starting point','Map a small, achievable project','Build workflows, APIs or an AI agent together','Debug, test and plan your next steps'],['A focused learning plan','A reviewed project','A clear next-step roadmap']),
 course('ai-automation-course','AI Automation Course','AI Automation Course (n8n + AI Agents)','An AI automation course teaches you to combine workflow tools, APIs and language models into useful systems. Aarvan Labs in Chennai teaches n8n and AI agents through practical builds and testing.',['Students','Freelancers','Operations teams'],['Workflow basics: triggers, data and expressions','APIs, webhooks and credentials','Build a lead capture workflow in n8n','Connect an AI model and business knowledge','Add tool boundaries, retries and human review','Build and present a working automation project'],['A lead routing workflow','A grounded AI assistant prototype','Experience testing and debugging workflows']),
 course('whatsapp-automation-course','WhatsApp Automation Training','WhatsApp Automation Training','WhatsApp automation training teaches you to design and connect business messaging workflows. Aarvan Labs in Chennai guides you from WhatsApp Cloud API concepts to a practical enquiry flow with human handover.',['Business owners','Freelancers','Support teams'],['Business account and WhatsApp Cloud API fundamentals','Webhooks and incoming message handling','Conversation design and approved templates','Connect a CRM or booking workflow','Add consent, opt-out and human handover','Test a real business enquiry project'],['A documented messaging flow','A tested integration prototype','A handover and maintenance checklist']),
 course('seo-aeo-for-business','SEO, AEO & GEO Training','SEO, AEO & GEO Training for Businesses','SEO, AEO and GEO training explains how websites can be discovered, understood and referenced by search and AI answer engines. Aarvan Labs in Chennai teaches businesses to improve accessible content and run a hands-on audit with the GEO Audit Engine.',['Business owners','Marketing teams','Website builders'],['SEO fundamentals: crawling, indexing and intent','AEO: answering a clear question directly','GEO: consistent entities, evidence and useful sources','Review metadata, structure and internal links','Run a hands-on GEO Audit Engine review','Prioritize improvements and track visibility'],['A website audit','A prioritized content plan','An understanding of citation limits'])
];
learn[3].faqs.push(['Can you guarantee citations in ChatGPT, Gemini or Perplexity?','No. Clear, accurate, accessible content can help discovery, but each platform controls its own answers and citations.']);
export const homeFaq = [ ['What is Aarvan Labs?',company.description], ['What can you build for my business?','Websites, n8n workflows, custom AI agents, business automations, WhatsApp flows and voice AI receptionists.'], ['Do you teach as well as build?','Yes. Learn with Aarvan includes 1:1 mentorship and practical AI, WhatsApp and search visibility training.'], ['Can we work together outside Chennai?','Yes. Remote discovery, delivery and online learning can be arranged across India.'], ['Is Tamil support available?','Yes. We support conversations and learning in Tamil and English.'], ['How much does a project cost?','We quote after understanding the scope, integrations and ongoing support. Published prices are awaiting confirmation.'], ['How do I get started?','Book a free call or send the contact form with your goal and current setup.'] ];
export const processSteps = ['Discover — understand your goal and current workflow','Design — agree the scope, tools and success criteria','Build — implement, test and review together','Support — hand over the system and plan ongoing care'];
export const why = ['Real product experience with THOZHAN, NOVA and VISION OS','Tamil and English support','Focused scope and short delivery cycles','We teach you how the system works'];

const outcomes = ['Turn website visits into useful business enquiries','Move data between your tools without repetitive copying','Give your team an assistant grounded in business knowledge','Plan reliable AI systems with clear responsibilities','Keep leads and operational handoffs moving','Handle customer enquiries and hand over to your team','Answer calls and capture appointment requests'];
services.forEach((s,i)=>s.summary=outcomes[i]);
// Search intent is expressed in visible copy, not hidden keyword lists.
export const searchContent = {
 'website-development': {
  title:'Website Development Company in Chennai',
  description:'Website development company in Chennai for clinics, coaching centres and startups. Get business website design and discuss your project.',
  sections:[['Business website design in Chennai','Build a website for clinics, coaching centres or startups with clear service information, accessible enquiry forms and mobile-friendly layouts. Each page should help visitors understand what you offer and take the next step.'],['Looking for a Next.js developer in India?','Aarvan Labs can scope a Next.js website when your project needs dynamic features or integrations. For simpler business sites, we can use static pages that are easy to host and maintain.']]
 },
 'n8n-automation': {
  title:'n8n Automation Expert in Chennai',
  description:'Work with an n8n automation expert in Chennai. Connect business tools, automate routine work and hire an n8n developer for your workflow.',
  sections:[['Hire an n8n developer for your workflow','If you need an n8n workflow developer in India, start with the tools you use, the data you move and the exceptions your team handles. We scope the integrations, testing and maintenance before building.'],['n8n for small business','Start with one useful workflow: capture a lead, validate the details, update your CRM and notify the responsible person. Expand once the workflow is reliable and someone owns its upkeep.']],
  faqs:[['n8n vs Zapier: which is better for Indian small businesses?','The better fit depends on your integrations, workflow complexity, budget and maintenance capacity. Compare the actual workflow in both tools, including hosting, usage charges and who will resolve failures. Aarvan Labs can help assess those requirements before choosing.']]
 },
 'ai-agent-development': {
  title:'AI Agent Development Services',
  description:'AI agent development services for business workflows and support. Build a custom AI agent with approved tools and human handover. Book a call.',
  sections:[['A custom AI agent for your business','Connect business knowledge and approved actions to a defined task, such as answering admissions questions or preparing a lead summary. We agree where the agent can act and when it must ask a person.'],['Hire an AI agent developer','For AI chatbot development in India, bring sample questions, approved documents and the systems you want to connect. Aarvan Labs uses these to scope the agent, evaluate its answers and plan human handover.']]
 },
 'agentic-ai-system-design': {
  title:'Agentic AI System Design',
  description:'Agentic AI system design, multi-agent system consulting and AI agent architecture. Scope tools, permissions and evaluations with Aarvan Labs.',
  sections:[['AI agent architecture and multi-agent system consulting','Map each responsibility, shared data source and handoff before adding agents. We review whether separate agents improve the workflow and how their outputs will be checked.'],['MCP server development and integration planning','Define which business tools and data an MCP server should expose, who can access them and which operations need approval. Development scope follows a review of your APIs and security requirements.']]
 },
 'business-automation': {
  h1:'Business Process Automation India',title:'Business Process Automation India',
  description:'Business process automation in India for SMEs. Automate lead follow-up, connect your CRM and reduce repetitive work. Discuss your workflow.',
  sections:[['Automate lead follow-up','Route new enquiries to an owner, create follow-up tasks and flag overdue responses. Keep approvals and exceptions visible so automation supports your sales process.'],['CRM automation for small business','Connect enquiry forms, spreadsheets and CRM records to reduce duplicate entry. Our workflow automation for SMEs starts with clear rules for record matching, updates and failed integrations.']]
 },
 'whatsapp-automation': {
  title:'WhatsApp Automation for Business',
  description:'WhatsApp automation for business: chatbot flows, API setup in Chennai and appointment requests. Plan a customer enquiry workflow with Aarvan Labs.',
  sections:[['WhatsApp Business API setup in Chennai','We help scope account setup, incoming-message handling and business integrations. A WhatsApp chatbot for customers in India should use clear language and make it easy to reach a person.'],['WhatsApp appointment booking bot','Guide a customer from an enquiry to an appointment request, check availability through a suitable integration and route exceptions to your team. Clinics and coaching centres can start with one booking flow.']],
  faqs:[['How do I automate WhatsApp for my business?','Choose a specific workflow, review your WhatsApp Business API setup, then connect incoming messages to your CRM or booking tool. Add consent, opt-out handling and a route to a person, and test the flow before launch.']]
 },
 'ai-receptionist': {
  title:'AI Receptionist for Business',
  description:'AI receptionist for business enquiries and appointment requests. Explore Tamil voice AI and an AI call assistant for clinics. Book a call.',
  sections:[['A voice AI receptionist for your front desk','An AI phone answering service in India can handle agreed questions, collect caller details and pass a summary to staff. A useful first scope is an AI call assistant for clinics that captures appointment requests and escalates questions needing a person.'],['Tamil voice AI','Tamil and English calling flows need testing with your business vocabulary and realistic caller scenarios. Language quality, transfers and fallback behavior are reviewed with the selected voice provider.']],
  faqs:[['What is an AI receptionist and how much does it cost in India?','An AI receptionist answers calls and carries out agreed front-desk tasks, such as capturing enquiries or appointment requests. Cost depends on call volume, languages, integrations and support, with telephony and AI usage charges scoped separately. Aarvan Labs provides a quote after discovery; published prices are awaiting confirmation.']]
 },
 'ai-automation-course': {
  h1:'AI Automation Course in Chennai',title:'AI Automation Course in Chennai',
  description:'AI automation course in Chennai: learn n8n automation and build AI agents through practical projects. Explore beginner learning and book a session.',
  sections:[['Learn n8n automation from the basics','This n8n course for beginners starts with triggers, data and simple workflow steps before introducing APIs and AI. Build a small project, inspect each step and learn how to recover from errors.'],['An AI agents course for learners in India','Move from a basic workflow to an assistant that uses approved information and tools. Practice testing answers and deciding which actions need human review.']],
  faqs:[['How do I learn AI automation from scratch?','Start with a repetitive task you understand. Learn triggers, data and APIs, then build a simple n8n workflow. Add an AI model only where it helps, test with realistic examples and keep a person responsible for exceptions. Learn with Aarvan guides you through this process.']]
 },
 'whatsapp-automation-course': {
  h1:'WhatsApp Automation Course',title:'WhatsApp Automation Course',
  description:'WhatsApp automation course with practical chatbot flows and WhatsApp Business API training. Learn to build a business enquiry project with Aarvan.',
  sections:[['Learn WhatsApp chatbot development','Plan the conversation, capture the right details and build a handover to staff. The project connects what customers ask to a useful business outcome.'],['WhatsApp Business API training','Work through account concepts, webhooks, message handling and integrations. Test an enquiry or booking flow, including consent, opt-outs and cases that need a person.']]
 },
 'seo-aeo-for-business': {
  h1:'SEO and AEO Training for Business',title:'SEO and AEO Training for Business',
  description:'SEO and AEO training for business, with practical GEO training in Chennai. Audit your site and improve useful, accessible content. Book a session.',
  sections:[['GEO training in Chennai','Our generative engine optimization course for businesses in India covers clear entity information, useful source material and an actionable website audit. Use the GEO Audit Engine to identify issues and prioritize changes.'],['How to rank in ChatGPT: what can you actually improve?','There is no fixed ChatGPT results position that a course can promise. Focus on accurate, accessible pages that answer specific questions, explain your services and identify your business consistently. Review whether relevant answers cite your sources over time.']],
  faqs:[['What is AEO / GEO and how is it different from SEO?','SEO focuses on helping search engines discover and understand pages. AEO focuses on clearly answering questions, while GEO focuses on how content may be used or cited in generated answers. These practices overlap: useful content, crawlable pages and accurate information support all three.'],['How can a small business show up in ChatGPT answers?','Publish accessible pages explaining your services, location and real work. Keep your business name and contact information consistent, answer specific customer questions and support claims with evidence. These steps help make your business understandable, but inclusion or citation in ChatGPT answers is not guaranteed.']]
 },
 'one-on-one-mentorship': {
  h1:'One-on-One AI Automation Mentorship',title:'AI Mentor Chennai — 1:1 Automation Mentorship',
  description:'Find an AI mentor in Chennai for one-on-one AI automation mentorship. Build practical AI skills for engineering students and founders. Book a session.',
  sections:[['Learn AI automation as a student','Work on a manageable project alongside your studies. Build AI skills for engineering students through APIs, workflow design, debugging and practical evaluations, with guidance matched to your starting point.'],['Work with an AI mentor in Chennai','Arivumathi S, known as Arivu, teaches through Learn with Aarvan at Aarvan Labs. One-on-one AI automation mentorship gives students, founders and freelancers a place to review their project and understand the next step.']]
 }
};
for(const entry of [...services,...learn]) {
 const search=searchContent[entry.slug];
 if(search.h1) entry.h1=search.h1;
 entry.seoTitle=search.title;
 entry.seoDescription=search.description;
 entry.searchSections=search.sections;
 if(search.faqs) entry.faqs.push(...search.faqs);
}
homeFaq.push(['Who is the best AI automation developer in Chennai?','The best fit depends on your workflow, integrations and support needs. Compare relevant project examples, communication, testing and handover rather than relying on a broad ranking claim. Aarvan Labs offers AI automation development in Chennai alongside hands-on teaching; discuss your use case to see whether we are a fit.']);
